---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vdbench-pvc-claim
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "64G"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: vdbench
spec:
  template:
    metadata:
      name: vdbench
    spec:
      restartPolicy: Never
      containers:
        - name: vdbench
          image: kerryeon/rook-bench
          volumeMounts:
            - name: vdbench-vol
              mountPath: /mnt/bench
      volumes:
        - name: vdbench-vol
          persistentVolumeClaim:
            claimName: vdbench-pvc-claim
